services:
    rmcgirr83.editedpostsunread.listener:
        class: rmcgirr83\editedpostsunread\event\listener
        arguments:
            - '@dbal.conn'		
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
